# This file generates the GitHub Actions matrix
---
include:

  # totem bluetooth (no dongle)
  - board: xiao_ble
    shield: totem_left
    artifact-name: totem_central_left
  - board: xiao_ble
    shield: totem_right
    artifact-name: totem_peripheral_right

  # reset
  - board: xiao_ble
    shield: settings_reset
